imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    position: %debug_toolbar_position%
    intercept_redirects: "%debug_redirects%"