imports:
    - { resource: parameters.yml }
    - { resource: doctrine.yml }
    - { resource: security.yml }

framework:
    secret: %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
    templating:
        engines: ['twig']
    default_locale: "%locale%"
    session:
        handler_id: ~
    form:
        enabled: true
        csrf_protection:
            enabled: true
#            field_name: secretfield
    translator: { fallback: "%locale%" }

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                mappings:
                    DdpktsCmsBundle: ~
                    SonataUserBundle: ~

#
# user
#
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ddpkts\CmsBundle\Entity\User

    group:
        group_class: Ddpkts\CmsBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.noop

sonata_user:
    security_acl: true
    manager_type: orm
    class:
        user: Ddpkts\CmsBundle\Entity\User
        group: Ddpkts\CmsBundle\Entity\Group

#
# user ends
#

#
# admin
#
sonata_doctrine_orm_admin:
    entity_manager: ~

sonata_admin:
#    title: title
#    title_logo: bundles/sonataadmin/logo_title.png

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:
        sonata.user.block.account:

#
# admin ends
#