# File: app/config/doctrine.yml
doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: ~
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true